export default [
    // 第一层
    {
        id: 1,
        type: 0,
        top: 12.5,
        left: 12.5,
        click: false,
        zIndex: 1,
    },
    {
        id: 2,
        type: 0,
        top: 12.5,
        left: 37.5,
        click: false,
        zIndex: 1,
    },
    {
        id: 3,
        type: 1,
        top: 12.5,
        left: 62.5,
        click: false,
        zIndex: 1,
    },
    {
        id: 4,
        type: 0,
        top: 37.5,
        left:  12.5,
        click: false,
        zIndex: 1,
    },
    {
        id: 5,
        type: 0,
        top: 37.5,
        left: 37.5,
        click: false,
        zIndex: 1,
    },
    {
        id: 6,
        type: 1,
        top: 37.5,
        left: 62.5,
        click: false,
        zIndex: 1,
    },
    {
        id: 7,
        type: 1,
        top: 62.5,
        left: 12.5,
        click: false,
        zIndex: 1,
    },
    {
        id: 8,
        type: 0,
        top: 62.5,
        left: 37.5,
        click: false,
        zIndex: 1,
    },
    {
        id: 9,
        type: 2,
        top: 62.5,
        left: 62.5,
        click: false,
        zIndex: 1,
    },
    // 第2层
    {
        id: 10,
        type: 2,
        top: 12.5 + 5,
        left: 12.5,
        click: false,
        zIndex: 2,
    },
    {
        id: 11,
        type: 2,
        top: 12.5 + 5,
        left: 37.5,
        click: false,
        zIndex: 2,
    },
    {
        id: 12,
        type: 2,
        top: 12.5 + 5,
        left: 62.5,
        click: false,
        zIndex: 2,
    },
    {
        id: 13,
        type: 1,
        top: 37.5 + 5,
        left:  12.5,
        click: false,
        zIndex: 2,
    },
    {
        id: 14,
        type: 0,
        top: 37.5 + 5,
        left: 37.5,
        click: false,
        zIndex: 2,
    },
    {
        id: 15,
        type: 2,
        top: 37.5 + 5,
        left: 62.5,
        click: false,
        zIndex: 2,
    },
    {
        id: 16,
        type: 1,
        top: 62.5 + 5,
        left: 12.5,
        click: false,
        zIndex: 2,
    },
    {
        id: 17,
        type: 2,
        top: 62.5 + 5,
        left: 37.5,
        click: false,
        zIndex: 2,
    },
    {
        id: 18,
        type: 1,
        top: 62.5 + 5,
        left: 62.5,
        click: false,
        zIndex: 2,
    }
]
